Menu
summer17-csc648-team1/warehausmedia pull request #21
Opened 2017-08-01 21:45 UTC by jhuang28

@runongirlrunon navigate bar is completely fixed. login & log out will display properly.

2017-08-01 21:58 UTC, runongirlrunon commented on src/Template/Layout/default.ctp
> +        <?= $cakeDescription ?>
this line can be taken out, no need for it. also the line where the variable is declared, too.

2017-08-01 22:03 UTC, runongirlrunon commented
![screen shot 2017-08-01 at 3 00 53 pm](https://user-images.githubusercontent.com/11033865/28849122-827a1a50-76ca-11e7-937b-c1d8ede4f7fb.png)
Seeing this error when I run the server on your branch, can you fix please?

2017-08-01 22:04 UTC, runongirlrunon commented
Better screenshot: 
![screen shot 2017-08-01 at 3 03 47 pm](https://user-images.githubusercontent.com/11033865/28849168-b5725ef4-76ca-11e7-93c1-6dbff06bcadc.png)

2017-08-01 22:06 UTC, runongirlrunon requested changes
Some comments: 
1. The deprecation error should be fixed
2. The menu bar is not responsive to the size of the window, please fix so that it resizes itself accordingly 
3. It'd be helpful to add some sort of border to the default layout CSS so that the body of the content doesn't touch the edges of the window.

2017-08-02 00:18 UTC, jhuang28 commented
i fixed deprecation error, and when user log in the register button will disappear.
also I took out $cakeDescription

2017-08-02 20:51 UTC, runongirlrunon approved these changes

2017-08-02 20:51 UTC, merged

2017-08-02 20:57 UTC, runongirlrunon commented
This closes https://github.com/summer17-csc648-team1/warehausmedia/issues/14.